services:
  - type: web
    name: ocean-pulse
    env: static
    buildCommand: npm ci && npm run build
    staticPublishPath: dist
    # A lightweight health check path to help render determine service readiness
    healthCheckPath: /index.html
    autoDeploy: true
